#!/bin/bash -eu

CURRENT_BRANCH=$(git symbolic-ref --short HEAD)

echo "#### Deploying from branch: ${CURRENT_BRANCH} ####"

if [[ $CURRENT_BRANCH != 'master' ]]
then
    echo "#########################################################"
    echo "!!!!! WARNING: YOU AREN'T ON MASTER! REALLY DEPLOY? !!!!!"
    echo "#########################################################"
fi

read -p "Are you sure? (y/n)" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Building breadbox from ${CURRENT_BRANCH}! 👩‍🍳👨‍🍳"
    yarn build

    echo "Deploying! 🍞"
    firebase deploy
fi

